### PR TITLE
Basic Inline commands

### PR DESCRIPTION
**Pull request by marbetschar**
Added basic inline commands (`addTextInline`, `addImageInline`, `addTableInline`) to place objects next to each other on the same line.

This pull requests works around current limitations mentioned in https://github.com/Techprimate/TPPDF/issues/50

bildschirmfoto 2018-03-29 um 12 20 56

Please note that this does not work 100% under every circumstances. Known limitations:
- Inline items can only be added to content containers (`.contentLeft`,`.contentCenter` and `.contentRight`)
- `addTableInline` does **not** work for `.contentCenter` (only `.contentLeft` and `.contentRight`)
- Adding multiple inline items to the same container is not supported - except you have a block element in between (e.g.: `.addTextInline(.contentLeft, ...), .addSpace(), .addTextInline(.contentLeft, ...)`
- Image captions are not supported

For now it works good enough [till the rewrite of the new version is complete](https://github.com/Techprimate/TPPDF/issues/29). Hopefully inline items will be supported in the new version?

### CODE REVIEW

**Comment by techprimate-phil** [comment]
Hi @marbetschar sounds like you are trying to achieve the same as mentioned in #9 ?
If so, wouldn't it be easier to start a multi-column section where you can add elements to each section individually?

**Comment by marbetschar** [comment]
@techprimate-phil how would you define a multi column section? Can‘t figure out how to do this. Is there any example available?

**Comment by techprimate-phil** [comment]
Please rebase your pull-request to the current master branch and let's continue the concept planning in #9

**Comment by techprimate-phil** [comment]
As we are working on multi columns #9 and #62 I am closing this pull request

**Pull request closed without merging**
