### PR TITLE
Add Command to Set Minimum Offset

### PR DESCRIPTION
**Pull request by rcdilorenzo**
I needed to have this feature to handle a right-aligned image with tables on the left that will expand to full length after the image in the document.

**Opinion/Discussion:** First of all, thanks so much for this project. I'm using it in an update to an app called [FieldX Journal](https://itunes.apple.com/us/app/fieldx-journal/id607064685?mt=8) (since you wanted to know where you library is being used). Although I tested this pull-request directly in our project, I would highly recommend getting a set of unit tests for this project. You may already be doing this on your new branch, but I feel obligated to say this in case it has not yet been considered.

### CODE REVIEW

**Comment by rcdilorenzo** [comment]
@techprimate-phil It says the code needs to be refactored but I can't actually see the issue. Can you tell me why it's failing this PR?

**Comment by techprimate-phil** [comment]
Hi @rcdilorenzo, I think the project is currently not fulfilling the refactoring standards, therefore this warning is not that important right now.

About your feature, can you please explain this feature again. Are you trying to have an image next to an table and it should have an minimum offset to the top edge?

**Comment by rcdilorenzo** [comment]
I have a image that floats on the right, and the tables on the left flow around the image.

**Comment by techprimate-phil** [comment]
Could this be solved by either multicolumns #9 or text wrapping #28?

**Comment by rcdilorenzo** [comment]
Hmm... I think #28 would work if it was free-flowing text, but I don't think it would work for tables (unless the wrapping was extremely intelligent). If that were added upon, I think it would work. However, for now, it would be nice to merge it for now so that our application wouldn't point to a fork, but I understand if you think that it will be resolved later. 😄 For #9, I don't think that would work unless the columns could be dynamically shifted from full-width to half-width at any arbitrary point in the document.

Let me know your thoughts.

**Comment by techprimate-phil** [comment]
Hi, please rebase your pull-request and I will merge it afterwards.

**Comment by rcdilorenzo** [comment]
Wow. I didn't expect the `develop` branch to get merged in already. It may take me a little while to understand the new system, upgrade our work on it, and then rebase this pull request. Stay tuned.

**Comment by techprimate-phil** [comment]
I will close this pull request for now, please create another one or reopen this one if necessary

**Pull request closed without merging**
