### PR TITLE
Swift 4.0

### PR DESCRIPTION
**Pull request by StefaniOSApps**

### CODE REVIEW

**Comment by techprimate-phil** [comment]
First off, thank you for bringing in Swift 4 support!

**Comment by StefaniOSApps** [comment]
I'm still a bit new on Github. Yes, I wanted to add it to "develop".

**Comment by StefaniOSApps** [comment]
I think its finished. On my Xcode - no errors.

**Comment by techprimate-phil** [comment]
I think we also need to update the Travis CI configuration in the .travis.yml so it won't fail with swift 4

**Comment by StefaniOSApps** [comment]
need help for update .travis.yml to swift 4.0

**Comment by techprimate-phil** [comment]
I think we need to change the version in the file .swift-version

**Comment by techprimate-phil** [comment]
Thank you for your help, I am working on the develop branch on swift 4 conversion as it seems more complex than expected.

**Comment by StefaniOSApps** [comment]
Unfortunately, I'm stuck here. It just does not work.
.swift-version is now 4.0
.travis.yml - xcode is now v9.0 and iPhone 7 has iOS 11.0.1 .. but it doesn't work,

**Comment by techprimate-phil** [comment]
I see, I will take care of this in the upcoming days as I am busy right now. For now if the local build succeeds, configure your Podfile to use your fork/this pull request and I will keep you updated.

**Comment by techprimate-phil** [comment]
But keep in mind, the develop branch is unstable, as I am rebuilding the core of TPPDF for improved usability

**Comment by StefaniOSApps** [comment]
Why you did not change in brache "develop" the followings in TableObjekts.swift:

```
let attributes: [String: AnyObject] = [
                            NSForegroundColorAttributeName: cellStyle.colors.text,
                            NSFontAttributeName: cellStyle.font,
                            NSParagraphStyleAttributeName: paragraph
                        ]
```

TO

```
 let attributes: [NSAttributedStringKey: AnyObject] = [
                            NSAttributedStringKey.foregroundColor: cellStyle.colors.text,
                            NSAttributedStringKey.font: cellStyle.font
                        ]
```

**Comment by techprimate-phil** [comment]
Xcode used cached build files, therefore it started to mix swift 3 and swift 4 files. After a clean, it failed to compile therefore I noticed this mistake.

Thank you for your help! 
I will close this issue now as the develop branch is a working build on swift 4

**Pull request closed without merging**
