### PR TITLE
Add name property on PDFPageFormat

### PR DESCRIPTION
**Pull request by ptrkstr**
This PR allows retrieving the name of each page format i.e. A4, B3, US Letter etc.
The use case I had for this was wanting to give the user a choice in page format and needing a name to display to them.

### CODE REVIEW

**Comment by philprime** [comment]
Looks good, please change the destination branch to `develop` and rebase on the latest commit :)

**Comment by ptrkstr** [comment]
Hi @philprime I noticed your `master` is much infront of `develop`.
I started my commit from `master` cause it was newer. Would you like me to start my branch from develop as well?

**Comment by philprime** [comment]
You are right, the develop was not updated, but it should not have mattered, because it was only the Ruby dependencies. `develop` is now up to date

**Comment by philprime** [comment]
I believe it should not matter anyways, as I will squash your PR

**Comment by ptrkstr** [comment]
Sounds good 😄

**Comment by philprime** [comment]
Thank you for the contribution!

**Pull request merged**
